/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tads.calculadora;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JOptionPane;

/**
 *
 * @author 20241070130005
 */
public class Calc extends javax.swing.JFrame {

    /**
     * Creates new form calc
     */
    public Calc() {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonSoma = new javax.swing.JButton();
        jButtonMulti = new javax.swing.JButton();
        jButtonDiv = new javax.swing.JButton();
        jButtonSub = new javax.swing.JButton();
        numero2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        numero1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        sign = new javax.swing.JLabel();
        jLabelResult = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");

        jButtonSoma.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jButtonSoma.setText("+");
        jButtonSoma.setToolTipText("somar");
        jButtonSoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSomaActionPerformed(evt);
            }
        });

        jButtonMulti.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jButtonMulti.setText("×");
        jButtonMulti.setToolTipText("multiplicar");
        jButtonMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMultiActionPerformed(evt);
            }
        });

        jButtonDiv.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jButtonDiv.setText("÷");
        jButtonDiv.setToolTipText("dividir");
        jButtonDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDivActionPerformed(evt);
            }
        });

        jButtonSub.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jButtonSub.setText("-");
        jButtonSub.setToolTipText("subtrair");
        jButtonSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubActionPerformed(evt);
            }
        });

        numero2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        numero2.setToolTipText("número 2");
        numero2.setName("numero2"); // NOI18N
        numero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Número 2");

        numero1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        numero1.setToolTipText("número 1");
        numero1.setName("numero1"); // NOI18N
        numero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Número 1");

        sign.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        sign.setToolTipText("");

        jLabelResult.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelResult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelResult.setText("---");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(numero1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(15, 15, 15)
                                        .addComponent(sign, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(15, 15, 15)
                                        .addComponent(numero2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(66, 66, 66)
                                        .addComponent(jLabel2)
                                        .addGap(10, 10, 10)))
                                .addGap(12, 12, 12))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonSub, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonSoma, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonMulti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelResult)
                        .addGap(131, 131, 131))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jLabelResult)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(5, 5, 5)
                        .addComponent(numero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(numero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(sign, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonMulti)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDiv))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonSoma)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSub)))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void numero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numero1ActionPerformed

    private void numero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numero2ActionPerformed

    private void jButtonSomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSomaActionPerformed
        try { 
            
            if(this.numero1.getText().equals("") && this.numero2.getText().equals("")) {
                this.jLabelResult.setForeground(Color.black);
                this.jLabelResult.setFont(new Font("Segoe UI", Font.PLAIN, 36));
                this.jLabelResult.setText("---");
            } else {
                Double n1 = Double.valueOf(this.numero1.getText());
                Double n2 = Double.valueOf(this.numero2.getText());
                this.sign.setText("+");

                this.jLabelResult.setFont(new Font("Segoe UI", Font.PLAIN, 36));
                this.jLabelResult.setForeground(Color.black);
                this.jLabelResult.setText(String.valueOf(n1+n2));
            }
        } catch(java.lang.NumberFormatException e) {
            this.sign.setText("+");
            this.jLabelResult.setForeground(Color.red);
            this.jLabelResult.setFont(new Font("Segoe UI", Font.PLAIN, 20));
            this.jLabelResult.setText("Erro de entrada");
            JOptionPane.showMessageDialog(this, "Insira apenas números!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonSomaActionPerformed

    private void jButtonMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMultiActionPerformed
        try { 
            
            if(this.numero1.getText().equals("") && this.numero2.getText().equals("")) {
                this.jLabelResult.setForeground(Color.black);
                this.jLabelResult.setFont(new Font("Segoe UI", Font.PLAIN, 36));
                this.jLabelResult.setText("---");
            } else {
                Double n1 = Double.valueOf(this.numero1.getText());
                Double n2 = Double.valueOf(this.numero2.getText());
                this.sign.setText("×");

                this.jLabelResult.setFont(new Font("Segoe UI", Font.PLAIN, 36));
                this.jLabelResult.setForeground(Color.black);
                this.jLabelResult.setText(String.valueOf(n1*n2));
            }
        } catch(java.lang.NumberFormatException e) {
            this.sign.setText("×");
            this.jLabelResult.setForeground(Color.red);
            this.jLabelResult.setFont(new Font("Segoe UI", Font.PLAIN, 20));
            this.jLabelResult.setText("Erro de entrada");
            JOptionPane.showMessageDialog(this, "Insira apenas números!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonMultiActionPerformed

    private void jButtonSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubActionPerformed
        try { 
            
            if(this.numero1.getText().equals("") && this.numero2.getText().equals("")) {
                this.jLabelResult.setForeground(Color.black);
                this.jLabelResult.setFont(new Font("Segoe UI", Font.PLAIN, 36));
                this.jLabelResult.setText("---");
            } else {
                Double n1 = Double.valueOf(this.numero1.getText());
                Double n2 = Double.valueOf(this.numero2.getText());
                this.sign.setText("-");

                this.jLabelResult.setFont(new Font("Segoe UI", Font.PLAIN, 36));
                this.jLabelResult.setForeground(Color.black);
                this.jLabelResult.setText(String.valueOf(n1-n2));
            }
        } catch(java.lang.NumberFormatException e) {
            this.sign.setText("-");
            this.jLabelResult.setForeground(Color.red);
            this.jLabelResult.setFont(new Font("Segoe UI", Font.PLAIN, 20));
            this.jLabelResult.setText("Erro de entrada");
            JOptionPane.showMessageDialog(this, "Insira apenas números!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonSubActionPerformed

    private void jButtonDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDivActionPerformed
        try { 
            
            if(this.numero1.getText().equals("") && this.numero2.getText().equals("")) {
                this.jLabelResult.setForeground(Color.black);
                this.jLabelResult.setFont(new Font("Segoe UI", Font.PLAIN, 36));
                this.jLabelResult.setText("---");
            } else {
                Double n1 = Double.valueOf(this.numero1.getText());
                Double n2 = Double.valueOf(this.numero2.getText());
                this.sign.setText("÷");

                if(n2 == 0) {
                    throw new CustomException("Não é possível dividir por zero.");
                }
                    
                this.jLabelResult.setFont(new Font("Segoe UI", Font.PLAIN, 36));
                this.jLabelResult.setForeground(Color.black);
                this.jLabelResult.setText(String.valueOf(n1/n2));
            }
        } catch(java.lang.NumberFormatException e) {
            this.sign.setText("÷");
            this.jLabelResult.setForeground(Color.red);
            this.jLabelResult.setFont(new Font("Segoe UI", Font.PLAIN, 20));
            this.jLabelResult.setText("Erro de entrada");
            JOptionPane.showMessageDialog(this, "Insira apenas números!", "Erro", JOptionPane.ERROR_MESSAGE);
        } catch(CustomException e) {
            this.jLabelResult.setForeground(Color.red);
            this.jLabelResult.setFont(new Font("Segoe UI", Font.PLAIN, 20));
            this.jLabelResult.setText("Divisão por zero");
            JOptionPane.showMessageDialog(this, e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonDivActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDiv;
    private javax.swing.JButton jButtonMulti;
    private javax.swing.JButton jButtonSoma;
    private javax.swing.JButton jButtonSub;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelResult;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField numero1;
    private javax.swing.JTextField numero2;
    private javax.swing.JLabel sign;
    // End of variables declaration//GEN-END:variables
}
