/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "quadrado.h"

int *
power_1_svc(int *argp, struct svc_req *rqstp)
{
	static int  result;

    printf("Me pediram para calcular %d^2.\n", *argp);
	result = *argp * *argp;

	return &result;
}
