/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "soma.h"

float *
add_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static float  result;

	printf("A função add(%.2f, %.2f) foi chamada\n", argp->a, argp->b);
    result = argp->a + argp->b;

	return &result;
}

float *
sub_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static float  result;

	printf("A função sub(%.2f, %.2f) foi chamada\n", argp->a, argp->b);
    result = argp->a - argp->b;

	return &result;
}

float *
mult_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static float  result;

	printf("A função mult(%.2f, %.2f) foi chamada\n", argp->a, argp->b);
    result = argp->a * argp->b;

	return &result;
}

float *
div_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static float  result;

	printf("A função div(%.2f, %.2f) foi chamada\n", argp->a, argp->b);
    result = argp->a / argp->b;

	return &result;
}
