/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SOMA_H_RPCGEN
#define _SOMA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct numbers {
	float a;
	float b;
};
typedef struct numbers numbers;

#define ADD_PROG 0x23451111
#define ADD_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define add 1
extern  float * add_1(numbers *, CLIENT *);
extern  float * add_1_svc(numbers *, struct svc_req *);
#define sub 2
extern  float * sub_1(numbers *, CLIENT *);
extern  float * sub_1_svc(numbers *, struct svc_req *);
#define mult 3
extern  float * mult_1(numbers *, CLIENT *);
extern  float * mult_1_svc(numbers *, struct svc_req *);
#define div 4
extern  float * div_1(numbers *, CLIENT *);
extern  float * div_1_svc(numbers *, struct svc_req *);
extern int add_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define add 1
extern  float * add_1();
extern  float * add_1_svc();
#define sub 2
extern  float * sub_1();
extern  float * sub_1_svc();
#define mult 3
extern  float * mult_1();
extern  float * mult_1_svc();
#define div 4
extern  float * div_1();
extern  float * div_1_svc();
extern int add_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_numbers (XDR *, numbers*);

#else /* K&R C */
extern bool_t xdr_numbers ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SOMA_H_RPCGEN */
