/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "soma.h"


void
add_prog_1(char *host, float x, float y)
{
	CLIENT *clnt;

	float  *result_1;
	numbers  add_1_arg;
    add_1_arg.a = x;
    add_1_arg.b = y;

	float  *result_2;
	numbers  sub_1_arg;
    sub_1_arg.a = x;
    sub_1_arg.b = y;

	float  *result_3;
	numbers  mult_1_arg;
    mult_1_arg.a = x;
    mult_1_arg.b = y;

	float  *result_4;
	numbers  div_1_arg;
    div_1_arg.a = x;
    div_1_arg.b = y;

#ifndef	DEBUG
	clnt = clnt_create (host, ADD_PROG, ADD_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = add_1(&add_1_arg, clnt);
	if (result_1 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	} else {
        printf("%.2f + %.2f = %.2f\n", add_1_arg.a, add_1_arg.b, *result_1);
    }
	result_2 = sub_1(&sub_1_arg, clnt);
	if (result_2 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	} else {
        printf("%.2f - %.2f = %.2f\n", sub_1_arg.a, sub_1_arg.b, *result_2);
    }
	result_3 = mult_1(&mult_1_arg, clnt);
	if (result_3 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	} else {
        printf("%.2f * %.2f = %.2f\n", mult_1_arg.a, mult_1_arg.b, *result_3);
    }
	result_4 = div_1(&div_1_arg, clnt);
	if (result_4 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	} else {
        printf("%.2f / %.2f = %.2f\n", div_1_arg.a, div_1_arg.b, *result_4);
    }
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 4) {
		printf ("usage: %s server <float_a> <float_b>\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	add_prog_1 (host, atof(argv[2]), atof(argv[3]));
exit (0);
}
